#!/usr/bin/env python
"""
parse a MAVLink protocol XML file and generate a python implementation

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later

测试命令：
./tools/mavgen.py --lang='GDScript' --output=mavgen_test ../mavlink/message_definitions/v1.0/common.xml --wire-protocol=2.0 --strict-units
"""
from __future__ import print_function

from builtins import range

import os
import sys
import textwrap
from . import mavtemplate

t = mavtemplate.MAVTemplate()


def extend_with_type_info(extended, enable_type_annotations):
    types = {
        "int": ("int", 0),
        "bool": ("bool", False),
        "float": ("float", 0),
        "str": ("str", ""),
        "bytes": ("bytes", b""),
        "bytearray": ("bytearray", bytearray(b"")),
        "none": ("None", None),
        "object": ("object", None),
        "str_list": ("List[str]", None),
        "int_list": ("List[int]", None),
        "str_float_int": ("Union[str, float, int]", None),
        "any": ("Any", None),
        "mavlink": ('"MAVLink"', None),
        "mavlink_header": ("MAVLink_header", None),
        "mavlink_message": ("MAVLink_message", None),
        "mavlink_message_type": ('Type[MAVLink_message]', None),
        "mavlink_message_attr": ("Union[bytes, float, int]", None),
        "mavlink_message_assign_attr_list": (
            "List[Union[bytes, float, int, Sequence[float], Sequence[int]]]",
            None,
        ),
        "mavlink_message_list": ("List[MAVLink_message]", None),
        "mavlink_message_signed_callback": ('Callable[["MAVLink", int], bool]', None),
        "dict_str_to_str_float_int": ("Dict[str, Union[str, float, int]]", None),
        "dict_str_to_dict_int_to_enumentry": ("Dict[str, Dict[int, EnumEntry]]", None),
        "dict_int_to_str": ("Dict[int, str]", None),
        "dict_str_to_str": ("Dict[str, str]", None),
        "dict_int_int_int_to_int": ("Dict[Tuple[int, int, int], int]", None),
        "dict_int_to_mavlink_message_type": ("Dict[int, Type[MAVLink_message]]", None),
        "tuple_int": ("Tuple[int]", None),
        "tuple_int_int": ("Tuple[int, int]", None),
        "tuple_int_int_int": ("Tuple[int, int, int]", None),
        "tuple_bytes_five_int": ("Tuple[bytes, int, int, int, int, int]", None),
        "tuple_bytes_eight_int": ("Tuple[bytes, int, int, int, int, int, int, int, int]", None),
        "tuple_bytes_int_float_repeat": ("Tuple[Union[bytes, int, float], ...]", None),
        "intseq": ("Sequence[int]", None),
        "intseq_floatseq": ("Union[Sequence[int], Sequence[float]]", None),
        "args": ("Iterable[Any]", None),
        "kwargs": ("Mapping[str, Any]", None),
        "generic_callback": ("Callable[..., None]", None),
    }

    res = extended
    if enable_type_annotations:
        res[
            "typing_imports"
        ] = """from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Type, Union, cast"""
        for type_name, type_info in types.items():
            res["type_" + type_name] = ": " + type_info[0]
            res["type_" + type_name + "_ret"] = " -> " + type_info[0]
            res["type_" + type_name + "_cast"] = type_info[0]
            if type_info[1] is not None:
                res["type_" + type_name + "_default"] = (
                    ": " + type_info[0] + " = " + repr(type_info[1])
                )
            res["type_optional_" + type_name] = ": Optional[" + type_info[0] + "]"
            res["type_optional_" + type_name + "_ret"] = " -> Optional[" + type_info[0] + "]"
            res["type_optional_" + type_name + "_cast"] = "Optional[" + type_info[0] + "]"
            res["type_optional_" + type_name + "_default"] = (
                ": Optional[" + type_info[0] + "] = None"
            )

    else:
        res[
            "typing_imports"
        ] = '''

def cast(type_str, arg):
    """
    No-op for Python2 used instead of typing.cast()
    """
    return arg
'''
        for type_name, type_info in types.items():
            res["type_" + type_name] = ""
            res["type_" + type_name + "_ret"] = ""
            res["type_" + type_name + "_cast"] = '"' + type_info[0] + '"'
            if type_info[1] is not None:
                res["type_" + type_name + "_default"] = "=" + repr(type_info[1])
            res["type_optional_" + type_name] = ""
            res["type_optional_" + type_name + "_ret"] = ""
            res["type_optional_" + type_name + "_cast"] = '"Optional[' + type_info[0] + ']"'
            res["type_optional_" + type_name + "_default"] = "=None"

    return res


def generate_preamble(outf, msgs, basename, args, xml):
    print("Generating preamble")

    params = dict(xml)
    params["FILELIST"] = (",".join(args),)
    params["DIALECT"] = os.path.splitext(os.path.basename(basename))[0]

    t.write(
        outf,
        '''
"""
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: ${FILELIST}

Note: this file has been auto-generated. DO NOT EDIT

note: 签名、验签功能尚未完成
"""

extends Node
class_name MAVLink

var Struct = load("res://module/struct.gd")

const WIRE_PROTOCOL_VERSION = "${wire_protocol_version}"
const DIALECT = "${DIALECT}"

const MAVLINK_IGNORE_CRC = false

const PROTOCOL_MARKER_V1 = 0xFE
const PROTOCOL_MARKER_V2 = 0xFD
const HEADER_LEN_V1 = 6
const HEADER_LEN_V2 = 10

const MAVLINK_SIGNATURE_BLOCK_LEN = 13

const MAVLINK_IFLAG_SIGNED = 0x01

# some base types from mavlink_types.h
const MAVLINK_TYPE_CHAR = 0
const MAVLINK_TYPE_UINT8_T = 1
const MAVLINK_TYPE_INT8_T = 2
const MAVLINK_TYPE_UINT16_T = 3
const MAVLINK_TYPE_INT16_T = 4
const MAVLINK_TYPE_UINT32_T = 5
const MAVLINK_TYPE_INT32_T = 6
const MAVLINK_TYPE_UINT64_T = 7
const MAVLINK_TYPE_INT64_T = 8
const MAVLINK_TYPE_FLOAT = 9
const MAVLINK_TYPE_DOUBLE = 10

class x25crc:
	"""CRC-16/MCRF4XX - based on checksum.h from mavlink library"""

	var crc: int = 0xFFFF

	func _init(buf: PackedByteArray = []) -> void:
		if buf != null:
			accumulate(buf)

	func accumulate(buf: PackedByteArray) -> void:
		"""Add in some more bytes"""
		var accum: int = crc
		for b in buf:
			var tmp: int = b ^ (accum & 0xFF)
			tmp = (tmp ^ (tmp << 4)) & 0xFF
			accum = (accum >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)
		crc = accum

func test_initial_crc() -> void:
	var crc = x25crc.new()
	assert(crc.crc == 0xFFFF, "Initial CRC should be 0xFFFF")

func test_accumulate_single_byte() -> void:
	var crc = x25crc.new()
	crc.accumulate([0x01])
	assert(crc.crc != 0xFFFF, "CRC should change after accumulating a byte")

func test_accumulate_multiple_bytes() -> void:
	var crc = x25crc.new()
	crc.accumulate([0x01, 0x02, 0x03])
	assert(crc.crc != 0xFFFF, "CRC should change after accumulating multiple bytes")

func test_accumulate_empty_array() -> void:
	var crc = x25crc.new()
	var initial_crc = crc.crc
	crc.accumulate([])
	assert(crc.crc == initial_crc, "CRC should remain unchanged after accumulating an empty array")

func test_x25crc() -> void:
	# 运行测试
	test_initial_crc()
	test_accumulate_single_byte()
	test_accumulate_multiple_bytes()
	test_accumulate_empty_array()
	print("test_x25crc PASS")

class MAVLink_header:
	"""MAVLink message header"""

	var mlen: int
	var seq: int
	var srcSystem: int
	var srcComponent: int
	var msgId: int
	var incompat_flags: int
	var compat_flags: int

	# 构造函数
	func _init(msgId: int, incompat_flags: int = 0, compat_flags: int = 0, mlen: int = 0, seq: int = 0, srcSystem: int = 0, srcComponent: int = 0) -> void:
		self.mlen = mlen
		self.seq = seq
		self.srcSystem = srcSystem
		self.srcComponent = srcComponent
		self.msgId = msgId
		self.incompat_flags = incompat_flags
		self.compat_flags = compat_flags

	func pack(force_mavlink1: bool = false) -> PackedByteArray:
		var byte_array = PackedByteArray()

		if WIRE_PROTOCOL_VERSION == "2.0" and not force_mavlink1:
			byte_array.append(PROTOCOL_MARKER_V2)
			byte_array.append(mlen)
			byte_array.append(incompat_flags)
			byte_array.append(compat_flags)
			byte_array.append(seq)
			byte_array.append(srcSystem)
			byte_array.append(srcComponent)
			byte_array.append(msgId & 0xFF)
			byte_array.append((msgId >> 8) & 0xFF)
			byte_array.append((msgId >> 16) & 0xFF)
		else:
			byte_array.append(PROTOCOL_MARKER_V1)
			byte_array.append(mlen)
			byte_array.append(seq)
			byte_array.append(srcSystem)
			byte_array.append(srcComponent)
			byte_array.append(msgId)

		return byte_array

func test_mavlink_header_pack_v2():
	var header = MAVLink_header.new(12345, 0, 0, 10, 1, 1, 1)
	var packed_data = header.pack(false)
	assert(packed_data.size() == 10)  # 根据实际打包的字节数进行调整
	assert(packed_data[0] == PROTOCOL_MARKER_V2)  # 检查协议标记
	assert(packed_data[1] == 10)  # 检查 mlen
	assert(packed_data[4] == 1)  # 检查 seq
	assert(packed_data[5] == 1)  # 检查 srcSystem
	assert(packed_data[6] == 1)  # 检查 srcComponent
	assert(packed_data[7] == (12345 & 0xFF))  # 检查 msgId
	assert(packed_data[8] == ((12345 >> 8) & 0xFF))  # 检查 msgId
	assert(packed_data[9] == ((12345 >> 16) & 0xFF))  # 检查 msgId

func test_mavlink_header_pack_v1():
	var header = MAVLink_header.new(123, 0, 0, 10, 1, 1, 1)
	var packed_data = header.pack(true)
	assert(packed_data.size() == 6)  # 根据实际打包的字节数进行调整
	assert(packed_data[0] == PROTOCOL_MARKER_V1)  # 检查协议标记 V1
	assert(packed_data[1] == 10)  # 检查 mlen
	assert(packed_data[2] == 1)  # 检查 seq
	assert(packed_data[3] == 1)  # 检查 srcSystem
	assert(packed_data[4] == 1)  # 检查 srcComponent
	assert(packed_data[5] == 123)  # 检查 msgId

func test_mavlink_header():
	test_mavlink_header_pack_v2()
	# note: 要测试v1需要手动修改常量WIRE_PROTOCOL_VERSION
	# test_mavlink_header_pack_v1()
	print("test_mavlink_header PASS")

class MAVLink_message:
	"""Base MAVLink message class"""

	# note: MAVLink_message基类中的字段加下划线，避免与自动生成代码冲突
	# 消息相关的静态数据
	var _id: int = 0
	var _msgname: String = ""
	var _fieldnames: Array = []
	var _ordered_fieldnames: Array = []
	var _fieldtypes: Array = []
	var _orders: Array = []
	var _lengths: Array = []
	var _array_lengths: Array = []
	var _crc_extra: int = 0
	var _instance_field = null # String 或者 null
	var _instance_offset: int = -1
	var _fmt: String
	func get_fieldnames() -> Array:
		return _fieldnames
	func get_orders() -> Array:
		return _orders
	func get_lengths() -> Array:
		return _lengths
	func get_crc_extra() -> int:
		return _crc_extra
	func get_fmt() -> String:
		return _fmt


	#var _fielddisplays_by_name: Dictionary = {}
	#var _fieldenums_by_name: Dictionary = {}
	#var _fieldunits_by_name: Dictionary = {}
	var _native_format: PackedByteArray = PackedByteArray()
	var _header: MAVLink_header
	var _payload: PackedByteArray
	var _msgbuf: PackedByteArray
	var _crc: int = 0
	var _typename: String
	var _signed: bool = false
	var _link_id: int = 0
	var _instances: Dictionary

	func _init(msgId: int, name: String) -> void:
		_header = MAVLink_header.new(msgId)
		self._typename = name

	func format_attr(field: String) -> Variant:
		"""Override field getter"""
		var raw_attr = self.get(field)
		if typeof(raw_attr) == TYPE_DICTIONARY:
			return raw_attr
		if typeof(raw_attr) == TYPE_ARRAY:
			return raw_attr
		if typeof(raw_attr) == TYPE_STRING:
			return raw_attr.strip_edges()
		return raw_attr

	func get_msgbuf() -> PackedByteArray:
		return _msgbuf
	func get_header() -> MAVLink_header:
		return _header
	func get_payload() -> PackedByteArray:
		return _payload
	func get_crc() -> int:
		return _crc
	func get_typename() -> String:
		return _typename
	func get_msgId() -> int:
		return _header.msgId
	func get_srcSystem() -> int:
		return _header.srcSystem
	func get_srcComponent() -> int:
		return _header.srcComponent
	func get_seq() -> int:
		return _header.seq
	func get_signed() -> bool:
		return _signed
	func get_link_id() -> int:
		return _link_id

	func _to_string() -> String:
		var ret = "%s {" % _typename
		for a in _fieldnames:
			var v = format_attr(a)
			ret += "%s : %s, " % [a, v]
		ret = ret.substr(0, ret.length() - 2) + "}"
		return ret

	func __ne__(other: Object) -> bool:
		return not self.__eq__(other)

	func __eq__(other: Object) -> bool:
		if other == null:
			return false

		if not other is MAVLink_message:
			return false

		if get_typename() != other.get_typename():
			return false

		if get_crc() != other.get_crc():
			return false

		if get_seq() != other.get_seq():
			return false

		if get_srcSystem() != other.get_srcSystem():
			return false

		if get_srcComponent() != other.get_srcComponent():
			return false

		for a in _fieldnames:
			if format_attr(a) != other.format_attr(a):
				return false

		return true

	func to_dict() -> Dictionary:
		var d: Dictionary = {}
		d["mavpackettype"] = _typename
		for a in _fieldnames:
			d[a] = format_attr(a)
		return d

	#func to_json() -> String:
	#	return JSON.print(to_dict())

	func sign_packet(mav: MAVLinkContext) -> void:
		assert(mav.signing.secret_key != null)

		var crypto = Crypto.new()
		var data_to_sign = _msgbuf  # 需要签名的数据
		var signature = crypto.sign(HashingContext.HASH_SHA256, data_to_sign, mav.signing.secret_key)

		_msgbuf.append_array(signature)  # 将签名附加到消息缓冲区
		mav.signing.timestamp += 1

	func _pack(mav: MAVLinkContext, crc_extra: int, payload: PackedByteArray, force_mavlink1: bool = false) -> PackedByteArray:
		var plen = payload.size()
		if WIRE_PROTOCOL_VERSION == "2.0" and not force_mavlink1:
			while plen > 1 and payload[plen - 1] == 0:
				plen -= 1
		payload = payload.slice(0, plen)
		var incompat_flags = 0
		if mav.signing.sign_outgoing:
			incompat_flags |= MAVLINK_IFLAG_SIGNED
		_header = MAVLink_header.new(
			_header.msgId,
			incompat_flags,
			0,
			payload.size(),
			mav.seq,
			mav.srcSystem,
			mav.srcComponent
		)
		_msgbuf = PackedByteArray(_header.pack(force_mavlink1))
		_msgbuf.append_array(payload)
		var tmpcrc = x25crc.new(_msgbuf.slice(1, _msgbuf.size()))
		if crc_extra != 0:
			tmpcrc.accumulate(PackedByteArray([crc_extra]))
		_crc = tmpcrc.crc
		_msgbuf.resize(_msgbuf.size() + 2)
		_msgbuf.encode_u16(_msgbuf.size() - 2, _crc)
		if mav.signing.sign_outgoing and not force_mavlink1:
			sign_packet(mav)
		return _msgbuf

	func pack(mav: MAVLinkContext, force_mavlink1: bool = false) -> PackedByteArray:
		push_error("MAVLink_message cannot be serialized directly")
		return PackedByteArray()

	func __getitem__(key: String) -> Variant:
		"""Support indexing, allowing for multi-instance sensors in one message"""
		if _instances == null:
			push_error("IndexError: _instances is null.")
			return null
		if not _instances.has(key):
			push_error("IndexError: Key '%s' not found in _instances." % key)
			return null
		return _instances[key]
''',
        params,
    )


def generate_enums(outf, enums, enable_type_annotations):
    print("Generating enums")

    type_info = extend_with_type_info({}, enable_type_annotations)

    t.write(outf, """\n# enums\n""", type_info,)
    for e in enums:
        outf.write("\n# %s\n" % e.name)
        for entry in e.entry:
            outf.write("const %s = %u\n" % (entry.name, entry.value))

    t.write(
        outf,
        """

class EnumEntry:
	var name: String
	var description: String
	var param: Dictionary = {}
	var has_location: bool = false

	# 构造函数
	func _init(name: String, description: String) -> void:
		self.name = name
		self.description = description

var enums: Dictionary = {}
func initialize_enums() -> void:
""",
        type_info,
    )

    for e in enums:
        outf.write("\n	# %s\n" % e.name)
        outf.write('	enums["%s"] = {}\n' % e.name)
        for entry in e.entry:
            description = entry.description.replace("\t", "    ")
            if "\n" in description:
                outf.write(
                    '	enums["%s"][%d] = EnumEntry.new(\n    "%s",\n    """%s""",\n)\n'
                    % (e.name, int(entry.value), entry.name, description)
                )
            else:
                outf.write(
                    '	enums["%s"][%d] = EnumEntry.new("%s", """%s""")\n'
                    % (e.name, int(entry.value), entry.name, description)
                )
            if entry.has_location:
                outf.write('	enums["%s"][%d].has_location = true\n' %
                           (e.name, int(entry.value),))
            for param in entry.param:
                description = param.description.replace("\t", "    ")
                if "\n" in description:
                    outf.write(
                        '	enums["%s"][%d].param[\n    %d\n] = """%s"""\n'
                        % (e.name, int(entry.value), int(param.index), description)
                    )
                else:
                    outf.write(
                        '	enums["%s"][%d].param[%d] = """%s"""\n'
                        % (e.name, int(entry.value), int(param.index), description)
                    )


def generate_message_ids(outf, msgs):
    print("Generating message IDs")
    outf.write("\n# message IDs\n")
    outf.write("const MAVLINK_MSG_ID_BAD_DATA = -1\n")
    outf.write("const MAVLINK_MSG_ID_UNKNOWN = -2\n")
    for m in msgs:
        outf.write("const MAVLINK_MSG_ID_%s = %u\n" % (m.name.upper(), m.id))


def byname_hash_from_field_attribute(m, attribute):
    strings = []
    for field in m.fields:
        value = getattr(field, attribute, None)
        if value is None or value == "":
            continue
        if attribute == "units":
            # hack; remove the square brackets further up
            if value[0] == "[":
                value = value[1:-1]
        strings.append('"%s": "%s"' % (field.name, value))
    return ", ".join(strings)


def generate_classes(outf, msgs, enable_type_annotations):
    print("Generating class definitions")
    wrapper = textwrap.TextWrapper(initial_indent="    ", subsequent_indent="    ")
    for m in msgs:
        classname = "MAVLink_%s_message" % m.name.lower()
        fieldname_str = ", ".join(['"s_%s"' % s for s in m.fieldnames])
        ordered_fieldname_str = ", ".join(['"%s"' % s for s in m.ordered_fieldnames])
        fielddisplays_str = byname_hash_from_field_attribute(m, "display")
        fieldenums_str = byname_hash_from_field_attribute(m, "enum")
        fieldunits_str = byname_hash_from_field_attribute(m, "units")

        fieldtypes_str = ", ".join(['"%s"' % s for s in m.fieldtypes])
        if m.instance_field is not None:
            instance_field = '"%s"' % m.instance_field
            instance_offset = m.field_offsets[m.instance_field]
        else:
            instance_field = "null"
            instance_offset = -1

        arg_fields = []
        for i in range(len(m.fields)):
            fname = m.fieldnames[i]
            arg_fields.append("%s: %s" % (fname, mavpytype(m.fields[i])))

        arg_fields_no_types = []
        for i in range(len(m.fields)):
            fname = m.fieldnames[i]
            arg_fields_no_types.append(fname)

        set_array_fields = []
        for i in range(len(m.fields)):
            f = m.fields[i]
            set_array_fields.append("self.s_%s = args[%d]" % (f.name, i))

        fields_vars = []
        for i in range(len(m.fields)):
            fname = m.fieldnames[i]
            if m.extensions_start is not None and i >= m.extensions_start:
                fdefault = m.fielddefaults[i]
                fields_vars.append("var s_%s: %s = %s" % (fname, mavpytype(m.fields[i]), fdefault))
            else:
                fields_vars.append("var s_%s: %s" % (fname, mavpytype(m.fields[i])))

        pack_fields = []
        for field in m.ordered_fields:
            if field.array_length == 0:
                pack_fields.append("self.s_{0:s}".format(field.name))
            else:
                for i in range(field.array_length):
                    pack_fields.append("self.s_{0:s}[{1:d}]".format(field.name, i))



        t.write(
            outf,
            '''

class ${classname}:
	extends MAVLink_message
	"""
${docstring}
	"""
	const ID = MAVLINK_MSG_ID_${msg_name_upper}
	const MSGNAME = "${msg_name_upper}"

	${fields_vars}

	func _init() -> void:
		super._init(ID, MSGNAME)
		_id = ID
		_msgname = MSGNAME
		_fieldnames = [${field_names}]
		_ordered_fieldnames = [${ordered_field_names}]
		_fieldtypes = [${field_types}]
		_orders = ${orders}
		_lengths = ${lengths}
		_array_lengths = ${array_lengths}
		_crc_extra = ${crc_extra}
		_instance_field = ${instance_field}
		_instance_offset = ${instance_offset}
		_fmt = "${native_fmtstr}"
	func set_array(args : Array) -> void:
		assert(args.size() == ${fields_count})
		${set_array_fields}
	func set_args(${arg_fields}) -> void:
		set_array([${arg_fields_no_types}])

	func pack(mav: MAVLinkContext, force_mavlink1: bool = false) -> PackedByteArray:
		var packed_data: PackedByteArray
		packed_data = Struct.pack(_fmt, [${pack_fields}])
		return self._pack(mav, _crc_extra, packed_data, force_mavlink1)

''',
            extend_with_type_info(
                {
                    "classname": classname,
                    "docstring": wrapper.fill(m.description.strip()),
                    "msg_name_upper": m.name.upper(),
                    "field_names": fieldname_str,
                    "ordered_field_names": ordered_fieldname_str,
                    "field_types": fieldtypes_str,
                    "field_displays": fielddisplays_str,
                    "field_nums": fieldenums_str,
                    "field_units": fieldunits_str,
                    "fmtstr": m.fmtstr,
                    "native_fmtstr": m.native_fmtstr,
                    "orders": m.order_map,
                    "lengths": m.len_map,
                    "array_lengths": m.array_len_map,
                    "crc_extra": m.crc_extra,
                    "instance_field": instance_field,
                    "instance_offset": instance_offset,
                    "arg_fields": ", ".join(arg_fields),
                    "set_array_fields": "\n		".join(set_array_fields),
                    "pack_fields": ", ".join(pack_fields),
                    "fields_vars": "\n	".join(fields_vars),
                    "arg_fields_no_types": ", ".join(arg_fields_no_types),
                    "fields_count": len(arg_fields),
                },
                enable_type_annotations,
            ),
        )


def native_mavfmt(field):
    """Work out the struct format for a type."""
    map = {
        "float": "f",
        "double": "d",
        "char": "c",
        "int8_t": "b",
        "uint8_t": "B",
        "uint8_t_mavlink_version": "v",
        "int16_t": "h",
        "uint16_t": "H",
        "int32_t": "i",
        "uint32_t": "I",
        "int64_t": "q",
        "uint64_t": "Q",
    }
    return map[field.type]


def mavfmt(field):
    """work out the struct format for a type"""
    map = {
        "float": "f",
        "double": "d",
        "char": "c",
        "int8_t": "b",
        "uint8_t": "B",
        "uint8_t_mavlink_version": "B",
        "int16_t": "h",
        "uint16_t": "H",
        "int32_t": "i",
        "uint32_t": "I",
        "int64_t": "q",
        "uint64_t": "Q",
    }

    if field.array_length:
        if field.type == "char":
            return str(field.array_length) + "s"
        return str(field.array_length) + map[field.type]
    return map[field.type]


def mavpytype(field):
    c_type_to_py = {
        "float": "float",
        "double": "float",
        "char": "PackedByteArray",
        "int8_t": "int",
        "uint8_t": "int",
        "uint8_t_mavlink_version": "int",
        "int16_t": "int",
        "uint16_t": "int",
        "int32_t": "int",
        "uint32_t": "int",
        "int64_t": "int",
        "uint64_t": "int",
    }

    if field.array_length:
        if field.type == "char":
            return "PackedByteArray"
        return "Array[{}]".format(c_type_to_py[field.type])
    return c_type_to_py[field.type]


def mavdefault(field):
    """returns default value for field (as string) for mavlink2 extensions"""
    if field.type == "char":
        return '[]'
    else:
        if field.array_length == 0:
            return "0"
        else:
            return "[" + ", ".join(["0"] * field.array_length) + "]"


def generate_mavlink_class(outf, msgs, xml):
    print("Generating MAVLink class")

    t.write(
        outf,
        """

const mavlink_map: Dictionary = {
""",
        xml,
    )
    for m in msgs:
        outf.write(
            "	# MAVLINK_MSG_ID_%s\n	%d: MAVLink_%s_message,\n" % (m.name.upper(), m.id, m.name.lower())
        )
    outf.write("}\n\n")

    t.write(
        outf,
        '''
class MAVLink_bad_data:
	extends MAVLink_message
	"""
	a piece of bad data in a mavlink stream
	"""

	var data: PackedByteArray
	var reason: String

	func _init(data: PackedByteArray, reason: String) -> void:
		super._init(MAVLINK_MSG_ID_BAD_DATA, "BAD_DATA")
		_id = MAVLINK_MSG_ID_BAD_DATA
		_msgname = "BAD_DATA"
		self.data = data
		self.reason = reason
		self._msgbuf = data.duplicate()  # 使用 duplicate() 复制 PoolByteArray

class MAVLink_unknown:
	extends MAVLink_message
	"""
	a message that we don't have in the XML used when built
	"""

	var data: PackedByteArray

	func _init(msgid: int, data: PackedByteArray) -> void:
		super._init(MAVLINK_MSG_ID_UNKNOWN, "UNKNOWN_%u" % msgid)
		_id = MAVLINK_MSG_ID_BAD_DATA
		_msgname = "BAD_DATA"
		self.data = data
		self._msgbuf = data.duplicate()  # 使用 duplicate() 复制 PoolByteArray

class MAVLinkSigning:
	"""MAVLink signing state class"""
	var secret_key = null # CryptoKey or null
	var timestamp = 0
	var link_id = 0
	var sign_outgoing = false
	# note: 当启用签名后，用allow_unsigned_callback询问用户程序是否允许某种msgId不使用签名
	# todo: 回调还不知道怎么实现
	# var allow_unsigned_callback: Optional[Callable[["MAVLink", int], bool]] = None
	# todo: 暂不知道怎么实现
	# var stream_timestamps: Dict[Tuple[int, int, int], int] = {}
	var sig_count = 0
	var badsig_count = 0
	var goodsig_count = 0
	var unsigned_count = 0
	var reject_count = 0

class MAVLinkContext:
	"""MAVLink protocol handling class"""
	var seq: int = 0
	var srcSystem: int
	var srcComponent: int
	var buf: PackedByteArray = PackedByteArray()
	var buf_index: int = 0
	var expected_length: int = HEADER_LEN_V1 + 2
	var have_prefix_error: bool = false
	var robust_parsing: bool = false

	var total_bytes_received: int = 0
	var total_packets_received: int = 0
	var total_receive_errors: int = 0
	var signing: MAVLinkSigning

	var mav20_unpacker : Struct
	var mav10_unpacker : Struct
	var mav20_h3_unpacker : Struct
	var mav_csum_unpacker : Struct
	var mav_sign_unpacker : Struct

	func _init(srcSystem: int, srcComponent: int) -> void:
		self.srcSystem = srcSystem
		self.srcComponent = srcComponent

		mav20_unpacker = Struct.new("<BBBBBBBBBB")
		mav10_unpacker = Struct.new("<BBBBBB")
		mav20_h3_unpacker = Struct.new("BBB")
		mav_csum_unpacker = Struct.new("<H")
		mav_sign_unpacker = Struct.new("<IH")

		signing = MAVLinkSigning.new()

	func parse_char(c: PackedByteArray) -> Variant:
		"""input some data bytes, possibly returning a new message"""
		buf.append_array(c)
		total_bytes_received += c.size()

		var m = _parse_char_legacy()

		if m != null:
			total_packets_received += 1
			#_callbacks(m)
		else:
			if buf.size() == 0 and buf_index != 0:
				buf.clear()
				buf_index = 0

		return m

	func _parse_char_legacy() -> Variant:
		"""input some data bytes, possibly returning a new message"""
		var header_len: int = HEADER_LEN_V1
		if buf.size() >= 1 and buf[buf_index] == PROTOCOL_MARKER_V2:
			header_len = HEADER_LEN_V2

		var m: Variant = null
		var magic: int = 0
		var incompat_flags: int = 0
		if buf.size() >= 1 and buf[buf_index] != PROTOCOL_MARKER_V1 and buf[buf_index] != PROTOCOL_MARKER_V2:
			magic = buf[buf_index]
			buf_index += 1
			if robust_parsing:
				m = MAVLink_bad_data.new(PackedByteArray([magic]), "Bad prefix")
				expected_length = header_len + 2
				total_receive_errors += 1
				return m
			if have_prefix_error:
				return null
			have_prefix_error = true
			total_receive_errors += 1
			push_error("invalid MAVLink prefix '%s'" % str(magic))

		have_prefix_error = false
		if buf.size() >= 3:
			var sbuf: PackedByteArray = buf.slice(buf_index, 3 + buf_index)
			var unpacked = mav20_h3_unpacker.unpack(sbuf)
			magic = unpacked[0]
			expected_length = unpacked[1]
			incompat_flags = unpacked[2]

			if magic == PROTOCOL_MARKER_V2 and (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
				expected_length += MAVLINK_SIGNATURE_BLOCK_LEN
			expected_length += header_len + 2

		if expected_length >= (header_len + 2) and buf.size() >= expected_length:
			var mbuf: PackedByteArray = buf.slice(buf_index, buf_index + expected_length)
			buf_index += expected_length
			expected_length = header_len + 2

			if robust_parsing:
				if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
					push_error("invalid incompat_flags 0x%x 0x%x %u" % [incompat_flags, magic, expected_length])
				m = decode(mbuf)
				if m == null:
					total_receive_errors += 1
			else:
				if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
					push_error("invalid incompat_flags 0x%x 0x%x %u" % [incompat_flags, magic, expected_length])
				m = decode(mbuf)
			return m

		return null

	func parse_buffer(s: PackedByteArray) -> Array:
		"""input some data bytes, possibly returning a list of new messages"""
		var m = parse_char(s)
		if m == null:
			return []
		var ret: Array = [m]
		while true:
			m = parse_char(PackedByteArray())
			if m == null:
				break
			ret.append(m)
		return ret

	func check_signature(msgbuf: PackedByteArray, srcSystem: int, srcComponent: int) -> bool:
		"""check signature on incoming message"""
		assert(signing.secret_key != null)

		var timestamp_buf: PackedByteArray = msgbuf.slice(-12, -6)
		var link_id: int = msgbuf[-13]
		var unpacked = mav_sign_unpacker.unpack(timestamp_buf)
		var tlow: int = unpacked[0]
		var thigh: int = unpacked[1]
		var timestamp: int = tlow + (thigh << 32)

		var stream_key: Dictionary = {"link_id": link_id, "srcSystem": srcSystem, "srcComponent": srcComponent}
		if stream_key in signing.stream_timestamps:
			if timestamp <= signing.stream_timestamps[stream_key]:
				push_error("old timestamp")
				return false
		else:
			if timestamp + 6000 * 1000 < signing.timestamp:
				push_error("bad new stream %s %s" % [timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365), signing.timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365)])
				return false
			signing.stream_timestamps[stream_key] = timestamp
			push_error("new stream")

		# 验签
		var h = Crypto.new()
		var data_to_checksign = msgbuf.slice(0, -6)
		var sig1 = h.sign(HashingContext.HASH_SHA256, data_to_checksign, signing.secret_key)
		var sig2: PackedByteArray = msgbuf.slice(-6, -1)
		if sig1 != sig2:
			push_error("sig mismatch")
			return false

		signing.timestamp = max(signing.timestamp, timestamp)
		return true

	func decode(msgbuf: PackedByteArray) -> Variant:
		"""decode a buffer as a MAVLink message"""
		var headerlen: int
		var unpacked
		var magic: int
		var mlen: int
		var incompat_flags: int
		var compat_flags: int
		var msgId: int
		var mapkey: int

		if msgbuf[0] == PROTOCOL_MARKER_V2:
			headerlen = 10
			unpacked = mav20_unpacker.unpack(msgbuf.slice(0, headerlen))
			if unpacked == null:
				push_error("Unable to unpack MAVLink header")
				return null

			magic = unpacked[0]
			mlen = unpacked[1]
			incompat_flags = unpacked[2]
			compat_flags = unpacked[3]
			seq = unpacked[4]
			srcSystem = unpacked[5]
			srcComponent = unpacked[6]
			msgId = unpacked[7] | (unpacked[8] << 8) | (unpacked[9] << 16)
			mapkey = msgId
		elif msgbuf[0] == PROTOCOL_MARKER_V1:
			headerlen = 6
			unpacked = mav10_unpacker.unpack(msgbuf.slice(0, headerlen))
			if unpacked == null:
				push_error("Unable to unpack MAVLink header")
				return null

			magic = unpacked[0]
			mlen = unpacked[1]
			seq = unpacked[2]
			srcSystem = unpacked[3]
			srcComponent = unpacked[4]
			msgId = unpacked[5]
			incompat_flags = 0
			compat_flags = 0
			mapkey = msgId

		var signature_len: int = 0
		if (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
			signature_len = MAVLINK_SIGNATURE_BLOCK_LEN

		if magic != PROTOCOL_MARKER_V1 and magic != PROTOCOL_MARKER_V2:
			push_error("invalid MAVLink prefix '%s'" % str(magic))
			return null
		if mlen != msgbuf.size() - (headerlen + 2 + signature_len):
			push_error("invalid MAVLink message length. Got %u expected %u, msgId=%u headerlen=%u" % [msgbuf.size() - (headerlen + 2 + signature_len), mlen, msgId, headerlen])
			return null


		if not (mapkey in mavlink_map):
			return MAVLink_unknown.new(msgId, msgbuf)

		var msgtype = mavlink_map[mapkey]
		var m = msgtype.new()
		if m == null:
			push_error("Unable to instantiate MAVLink message of type %s" % msgtype)
			return null

		var crc_data = msgbuf.slice(msgbuf.size()-2-signature_len, msgbuf.size()-signature_len)
		var crc: int = mav_csum_unpacker.unpack(crc_data)[0]
		var crc_calc = x25crc.new()
		crc_calc.accumulate(msgbuf.slice(1, - (2 + signature_len)))
		var crc_extra = m.get_crc_extra()
		if crc_extra:
			crc_calc.accumulate([crc_extra])

		if crc != crc_calc.crc and not MAVLINK_IGNORE_CRC:
			push_error("invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x" % [msgId, crc, crc_calc.crc])
			return null

		var sig_ok: bool = false
		if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
			signing.sig_count += 1
		if signing.secret_key != null:
			var accept_signature: bool = false
			if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
				sig_ok = check_signature(msgbuf, srcSystem, srcComponent)
				accept_signature = sig_ok
				if sig_ok:
					signing.goodsig_count += 1
				else:
					signing.badsig_count += 1
				if not accept_signature and signing.allow_unsigned_callback != null:
					# fixme: 应该从回调获取
					accept_signature = true
					# accept_signature = signing.allow_unsigned_callback(self, msgId)
					if accept_signature:
						signing.unsigned_count += 1
					else:
						signing.reject_count += 1
			elif signing.allow_unsigned_callback != null:
				# fixme: 应该从回调获取
				accept_signature = true
				# accept_signature = signing.allow_unsigned_callback(self, msgId)
				if accept_signature:
					signing.unsigned_count += 1
				else:
					signing.reject_count += 1
			if not accept_signature:
				push_error("Invalid signature")
				return null

		var unpacker = Struct.new(m.get_fmt())
		var csize: int = unpacker.get_size()
		var mbuf: PackedByteArray = msgbuf.slice(headerlen, - (2 + signature_len))
		if mbuf.size() < csize:
			mbuf.resize(csize)
		if mbuf.size() < csize:
			push_error("Bad message of type %s length %u needs %s" % [msgtype, mbuf.size(), csize])
			return null
		mbuf = mbuf.slice(0, csize)
		# 按经过排序的的参数顺序解出
		var t = unpacker.unpack(mbuf)
		if t == null:
			push_error("Unable to unpack MAVLink payload type=%s payloadLength=%u" % [msgtype, mbuf.size()])
			return null
		# 整理成原始的参数顺序
		var order_map = m.get_orders()
		var tlist: Array = []
		for order in order_map:
			tlist.append(t[order])

		m.set_array(tlist)
		m._signed = sig_ok
		if m._signed:
			m._link_id = msgbuf[-13]
		m._msgbuf = msgbuf
		m._payload = msgbuf.slice(6, - (2 + signature_len))
		m._crc = crc
		m._header = MAVLink_header.new(msgId, incompat_flags, compat_flags, mlen, seq, srcSystem, srcComponent)
		return m

func test_mavlink_endecode():
	const TEST_SRC_SYSTEM = 55
	const TEST_SRC_COMPONENT = 66

	var mav_ctx = MAVLinkContext.new(TEST_SRC_SYSTEM, TEST_SRC_COMPONENT)

	var encode_msg = MAVLink_heartbeat_message.new()
	encode_msg.set_args(1,2,3,4,5,6)
	print("encode_msg(heartbeat): %s" % encode_msg.to_string())

	var encode_data : PackedByteArray = encode_msg.pack(mav_ctx)
	print("encode_data: %s" % encode_data)

	var decode_msg = mav_ctx.decode(encode_data)
	print("decode_msg: %s" % decode_msg)

	assert(decode_msg != null)
	assert(decode_msg.get_typename() == encode_msg.get_typename())
	assert(decode_msg.s_type == encode_msg.s_type)
	assert(decode_msg.s_autopilot == encode_msg.s_autopilot)
	assert(decode_msg.s_base_mode == encode_msg.s_base_mode)
	assert(decode_msg.s_custom_mode == encode_msg.s_custom_mode)
	assert(decode_msg.s_system_status == encode_msg.s_system_status)
	assert(decode_msg.s_mavlink_version == encode_msg.s_mavlink_version)
	print("test_mavlink_endecode: PASSED")

func _init() -> void:
	initialize_enums()

	Struct.test_pack_unpack()
	test_x25crc()
	test_mavlink_header()
	test_mavlink_endecode()

''',
        xml,
    )

def generate(basename, xml, enable_type_annotations=False):
    """generate complete gdscript implementation"""
    if basename.endswith(".gd"):
        filename = basename
    else:
        filename = basename + ".gd"

    msgs = []
    enums = []
    filelist = []
    for x in xml:
        msgs.extend(x.message)
        enums.extend(x.enum)
        filelist.append(os.path.basename(x.filename))

    for m in msgs:
        m.fielddefaults = []
        if xml[0].little_endian:
            m.fmtstr = "<"
        else:
            m.fmtstr = ">"
        m.native_fmtstr = m.fmtstr
        m.instance_field = None
        for f in m.ordered_fields:
            m.fmtstr += mavfmt(f)
            m.fielddefaults.append(mavdefault(f))
            m.native_fmtstr += native_mavfmt(f)
            if f.instance:
                m.instance_field = f.name
        m.order_map = [0] * len(m.fieldnames)
        m.len_map = [0] * len(m.fieldnames)
        m.array_len_map = [0] * len(m.fieldnames)
        for i in range(0, len(m.fieldnames)):
            m.order_map[i] = m.ordered_fieldnames.index(m.fieldnames[i])
            m.array_len_map[i] = m.ordered_fields[i].array_length
        for i in range(0, len(m.fieldnames)):
            n = m.order_map[i]
            m.len_map[n] = m.fieldlengths[i]

    print("Generating %s" % filename)
    outf = open(filename, "w")
    xml = extend_with_type_info(xml[0].__dict__, enable_type_annotations)
    generate_preamble(outf, msgs, basename, filelist, xml)
    generate_enums(outf, enums, enable_type_annotations)
    generate_message_ids(outf, msgs)
    generate_classes(outf, msgs, enable_type_annotations)
    generate_mavlink_class(outf, msgs, xml)
    outf.close()
    print("Generated %s OK" % filename)
